/*
 *  Author: Mike Atkinson
 *
 *  This software has been developed under the copyleft
 *  rules of the GNU General Public License.  Please
 *  consult the GNU General Public License for more
 *  details about use and distribution of this software.
 */
package net.sourceforge.jrefactory.parser;

import net.sourceforge.jrefactory.ast.*;
import net.sourceforge.jrefactory.io.*;


/* Generated By:JJTree: Do not edit this line. JavaParserTreeConstants.java */

public interface JavaParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTPACKAGEDECLARATION = 1;
  public int JJTIMPORTDECLARATION = 2;
  public int JJTTYPEDECLARATION = 3;
  public int JJTCLASSDECLARATION = 4;
  public int JJTUNMODIFIEDCLASSDECLARATION = 5;
  public int JJTANNOTATION = 6;
  public int JJTMEMBERVALUEPAIRS = 7;
  public int JJTMEMBERVALUEPAIR = 8;
  public int JJTMEMBERVALUE = 9;
  public int JJTMEMBERVALUEARRAYINITIALIZER = 10;
  public int JJTTYPEPARAMETERS = 11;
  public int JJTTYPEPARAMETERLIST = 12;
  public int JJTTYPEPARAMETER = 13;
  public int JJTREFERENCETYPELIST = 14;
  public int JJTACTUALTYPEARGUMENT = 15;
  public int JJTCLASSBODY = 16;
  public int JJTNESTEDCLASSDECLARATION = 17;
  public int JJTJSPBODY = 18;
  public int JJTCLASSBODYDECLARATION = 19;
  public int JJTENUMDECLARATION = 20;
  public int JJTIDENTIFIER = 21;
  public int JJTENUMELEMENT = 22;
  public int JJTANNOTATIONTYPEDECLARATION = 23;
  public int JJTANNOTATIONTYPEMEMBERDECLARATION = 24;
  public int JJTANNOTATIONMETHODDECLARATION = 25;
  public int JJTCONSTANTDECLARATION = 26;
  public int JJTINTERFACEDECLARATION = 27;
  public int JJTNESTEDINTERFACEDECLARATION = 28;
  public int JJTUNMODIFIEDINTERFACEDECLARATION = 29;
  public int JJTINTERFACEBODY = 30;
  public int JJTINTERFACEMEMBERDECLARATION = 31;
  public int JJTFIELDDECLARATION = 32;
  public int JJTVARIABLEDECLARATOR = 33;
  public int JJTVARIABLEDECLARATORID = 34;
  public int JJTVARIABLEINITIALIZER = 35;
  public int JJTARRAYINITIALIZER = 36;
  public int JJTMETHODDECLARATION = 37;
  public int JJTMETHODDECLARATOR = 38;
  public int JJTFORMALPARAMETERS = 39;
  public int JJTFORMALPARAMETER = 40;
  public int JJTCONSTRUCTORDECLARATION = 41;
  public int JJTEXPLICITCONSTRUCTORINVOCATION = 42;
  public int JJTINITIALIZER = 43;
  public int JJTTYPE = 44;
  public int JJTREFERENCETYPE = 45;
  public int JJTTYPEARGUMENTS = 46;
  public int JJTPRIMITIVETYPE = 47;
  public int JJTRESULTTYPE = 48;
  public int JJTNAME = 49;
  public int JJTCLASSORINTERFACETYPE = 50;
  public int JJTNAMELIST = 51;
  public int JJTGENERICNAMELIST = 52;
  public int JJTEXPRESSION = 53;
  public int JJTASSIGNMENTOPERATOR = 54;
  public int JJTCONDITIONALEXPRESSION = 55;
  public int JJTCONDITIONALOREXPRESSION = 56;
  public int JJTCONDITIONALANDEXPRESSION = 57;
  public int JJTINCLUSIVEOREXPRESSION = 58;
  public int JJTEXCLUSIVEOREXPRESSION = 59;
  public int JJTANDEXPRESSION = 60;
  public int JJTEQUALITYEXPRESSION = 61;
  public int JJTINSTANCEOFEXPRESSION = 62;
  public int JJTRELATIONALEXPRESSION = 63;
  public int JJTSHIFTEXPRESSION = 64;
  public int JJTADDITIVEEXPRESSION = 65;
  public int JJTMULTIPLICATIVEEXPRESSION = 66;
  public int JJTUNARYEXPRESSION = 67;
  public int JJTPREINCREMENTEXPRESSION = 68;
  public int JJTPREDECREMENTEXPRESSION = 69;
  public int JJTUNARYEXPRESSIONNOTPLUSMINUS = 70;
  public int JJTPOSTFIXEXPRESSION = 71;
  public int JJTCASTEXPRESSION = 72;
  public int JJTPRIMARYEXPRESSION = 73;
  public int JJTPRIMARYPREFIX = 74;
  public int JJTPRIMARYSUFFIX = 75;
  public int JJTLITERAL = 76;
  public int JJTBOOLEANLITERAL = 77;
  public int JJTNULLLITERAL = 78;
  public int JJTARGUMENTS = 79;
  public int JJTARGUMENTLIST = 80;
  public int JJTALLOCATIONEXPRESSION = 81;
  public int JJTARRAYDIMSANDINITS = 82;
  public int JJTSTATEMENT = 83;
  public int JJTLABELEDSTATEMENT = 84;
  public int JJTBLOCK = 85;
  public int JJTBLOCKSTATEMENT = 86;
  public int JJTLOCALVARIABLEDECLARATION = 87;
  public int JJTEMPTYSTATEMENT = 88;
  public int JJTSTATEMENTEXPRESSION = 89;
  public int JJTSWITCHSTATEMENT = 90;
  public int JJTSWITCHLABEL = 91;
  public int JJTIFSTATEMENT = 92;
  public int JJTWHILESTATEMENT = 93;
  public int JJTFORSTATEMENT = 94;
  public int JJTFORINIT = 95;
  public int JJTDOSTATEMENT = 96;
  public int JJTSTATEMENTEXPRESSIONLIST = 97;
  public int JJTFORUPDATE = 98;
  public int JJTBREAKSTATEMENT = 99;
  public int JJTCONTINUESTATEMENT = 100;
  public int JJTRETURNSTATEMENT = 101;
  public int JJTTHROWSTATEMENT = 102;
  public int JJTSYNCHRONIZEDSTATEMENT = 103;
  public int JJTTRYSTATEMENT = 104;
  public int JJTASSERTIONSTATEMENT = 105;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "PackageDeclaration",
    "ImportDeclaration",
    "TypeDeclaration",
    "ClassDeclaration",
    "UnmodifiedClassDeclaration",
    "Annotation",
    "MemberValuePairs",
    "MemberValuePair",
    "MemberValue",
    "MemberValueArrayInitializer",
    "TypeParameters",
    "TypeParameterList",
    "TypeParameter",
    "ReferenceTypeList",
    "ActualTypeArgument",
    "ClassBody",
    "NestedClassDeclaration",
    "JSPBody",
    "ClassBodyDeclaration",
    "EnumDeclaration",
    "Identifier",
    "EnumElement",
    "AnnotationTypeDeclaration",
    "AnnotationTypeMemberDeclaration",
    "AnnotationMethodDeclaration",
    "ConstantDeclaration",
    "InterfaceDeclaration",
    "NestedInterfaceDeclaration",
    "UnmodifiedInterfaceDeclaration",
    "InterfaceBody",
    "InterfaceMemberDeclaration",
    "FieldDeclaration",
    "VariableDeclarator",
    "VariableDeclaratorId",
    "VariableInitializer",
    "ArrayInitializer",
    "MethodDeclaration",
    "MethodDeclarator",
    "FormalParameters",
    "FormalParameter",
    "ConstructorDeclaration",
    "ExplicitConstructorInvocation",
    "Initializer",
    "Type",
    "ReferenceType",
    "TypeArguments",
    "PrimitiveType",
    "ResultType",
    "Name",
    "ClassOrInterfaceType",
    "NameList",
    "GenericNameList",
    "Expression",
    "AssignmentOperator",
    "ConditionalExpression",
    "ConditionalOrExpression",
    "ConditionalAndExpression",
    "InclusiveOrExpression",
    "ExclusiveOrExpression",
    "AndExpression",
    "EqualityExpression",
    "InstanceOfExpression",
    "RelationalExpression",
    "ShiftExpression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "PreIncrementExpression",
    "PreDecrementExpression",
    "UnaryExpressionNotPlusMinus",
    "PostfixExpression",
    "CastExpression",
    "PrimaryExpression",
    "PrimaryPrefix",
    "PrimarySuffix",
    "Literal",
    "BooleanLiteral",
    "NullLiteral",
    "Arguments",
    "ArgumentList",
    "AllocationExpression",
    "ArrayDimsAndInits",
    "Statement",
    "LabeledStatement",
    "Block",
    "BlockStatement",
    "LocalVariableDeclaration",
    "EmptyStatement",
    "StatementExpression",
    "SwitchStatement",
    "SwitchLabel",
    "IfStatement",
    "WhileStatement",
    "ForStatement",
    "ForInit",
    "DoStatement",
    "StatementExpressionList",
    "ForUpdate",
    "BreakStatement",
    "ContinueStatement",
    "ReturnStatement",
    "ThrowStatement",
    "SynchronizedStatement",
    "TryStatement",
    "AssertionStatement",
  };
}
