/* Generated By:JJTree: Do not edit this line. ASTAssertionStatement.java */

public class ASTAssertionStatement extends SimpleNode {
  public ASTAssertionStatement(int id) {
    super(id);
  }

  public ASTAssertionStatement(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
