/* Generated By:JJTree: Do not edit this line. ASTConstantDeclaration.java */

public class ASTConstantDeclaration extends SimpleNode {
  public ASTConstantDeclaration(int id) {
    super(id);
  }

  public ASTConstantDeclaration(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
