/* Generated By:JJTree: Do not edit this line. ASTInterfaceBody.java */

public class ASTInterfaceBody extends SimpleNode {
  public ASTInterfaceBody(int id) {
    super(id);
  }

  public ASTInterfaceBody(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
