/* Generated By:JJTree: Do not edit this line. ASTIdentifier.java */

public class ASTIdentifier extends ASTLiteral {
  public ASTIdentifier(int id) {
    super(id);
  }

  public ASTIdentifier(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
