/* Generated By:JJTree: Do not edit this line. ASTJSPBody.java */

public class ASTJSPBody extends SimpleNode {
  public ASTJSPBody(int id) {
    super(id);
  }

  public ASTJSPBody(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
