/* Generated By:JJTree: Do not edit this line. ASTReferenceTypeList.java */

public class ASTReferenceTypeList extends SimpleNode {
  public ASTReferenceTypeList(int id) {
    super(id);
  }

  public ASTReferenceTypeList(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
