/* Generated By:JJTree: Do not edit this line. ASTTypeParameterList.java */

public class ASTTypeParameterList extends SimpleNode {
  public ASTTypeParameterList(int id) {
    super(id);
  }

  public ASTTypeParameterList(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
